// Curated list of common countries for Twilio messaging UI.
export type CountryOpt = { iso2: string; name: string; flag: string; dial: string };

export const COUNTRIES: CountryOpt[] = [
  { iso2: "US", name: "United States", flag: "🇺🇸", dial: "+1" },
  { iso2: "CA", name: "Canada", flag: "🇨🇦", dial: "+1" },
  { iso2: "GB", name: "United Kingdom", flag: "🇬🇧", dial: "+44" },
  { iso2: "IE", name: "Ireland", flag: "🇮🇪", dial: "+353" },
  { iso2: "NG", name: "Nigeria", flag: "🇳🇬", dial: "+234" },
  { iso2: "GH", name: "Ghana", flag: "🇬🇭", dial: "+233" },
  { iso2: "KE", name: "Kenya", flag: "🇰🇪", dial: "+254" },
  { iso2: "ZA", name: "South Africa", flag: "🇿🇦", dial: "+27" },
  { iso2: "IN", name: "India", flag: "🇮🇳", dial: "+91" },
  { iso2: "AE", name: "United Arab Emirates", flag: "🇦🇪", dial: "+971" },
  { iso2: "SA", name: "Saudi Arabia", flag: "🇸🇦", dial: "+966" },
  { iso2: "DE", name: "Germany", flag: "🇩🇪", dial: "+49" },
  { iso2: "FR", name: "France", flag: "🇫🇷", dial: "+33" },
  { iso2: "ES", name: "Spain", flag: "🇪🇸", dial: "+34" },
  { iso2: "IT", name: "Italy", flag: "🇮🇹", dial: "+39" },
  { iso2: "NL", name: "Netherlands", flag: "🇳🇱", dial: "+31" },
  { iso2: "BE", name: "Belgium", flag: "🇧🇪", dial: "+32" },
  { iso2: "CH", name: "Switzerland", flag: "🇨🇭", dial: "+41" },
  { iso2: "SE", name: "Sweden", flag: "🇸🇪", dial: "+46" },
  { iso2: "NO", name: "Norway", flag: "🇳🇴", dial: "+47" },
  { iso2: "DK", name: "Denmark", flag: "🇩🇰", dial: "+45" },
  { iso2: "PL", name: "Poland", flag: "🇵🇱", dial: "+48" },
  { iso2: "TR", name: "Turkey", flag: "🇹🇷", dial: "+90" },
  { iso2: "BR", name: "Brazil", flag: "🇧🇷", dial: "+55" },
  { iso2: "MX", name: "Mexico", flag: "🇲🇽", dial: "+52" },
  { iso2: "AR", name: "Argentina", flag: "🇦🇷", dial: "+54" },
  { iso2: "CO", name: "Colombia", flag: "🇨🇴", dial: "+57" },
  { iso2: "AU", name: "Australia", flag: "🇦🇺", dial: "+61" },
  { iso2: "NZ", name: "New Zealand", flag: "🇳🇿", dial: "+64" },
  { iso2: "JP", name: "Japan", flag: "🇯🇵", dial: "+81" },
  { iso2: "KR", name: "South Korea", flag: "🇰🇷", dial: "+82" },
  { iso2: "CN", name: "China", flag: "🇨🇳", dial: "+86" },
  { iso2: "HK", name: "Hong Kong", flag: "🇭🇰", dial: "+852" },
  { iso2: "SG", name: "Singapore", flag: "🇸🇬", dial: "+65" },
  { iso2: "MY", name: "Malaysia", flag: "🇲🇾", dial: "+60" },
  { iso2: "ID", name: "Indonesia", flag: "🇮🇩", dial: "+62" },
  { iso2: "TH", name: "Thailand", flag: "🇹🇭", dial: "+66" },
  { iso2: "PH", name: "Philippines", flag: "🇵🇭", dial: "+63" },
  { iso2: "VN", name: "Vietnam", flag: "🇻🇳", dial: "+84" },
  { iso2: "PT", name: "Portugal", flag: "🇵🇹", dial: "+351" },
  { iso2: "GR", name: "Greece", flag: "🇬🇷", dial: "+30" },
  { iso2: "AT", name: "Austria", flag: "🇦🇹", dial: "+43" },
  { iso2: "FI", name: "Finland", flag: "🇫🇮", dial: "+358" },
  { iso2: "CZ", name: "Czech Republic", flag: "🇨🇿", dial: "+420" },
  { iso2: "HU", name: "Hungary", flag: "🇭🇺", dial: "+36" },
  { iso2: "RO", name: "Romania", flag: "🇷🇴", dial: "+40" },
  { iso2: "IL", name: "Israel", flag: "🇮🇱", dial: "+972" },
  { iso2: "PK", name: "Pakistan", flag: "🇵🇰", dial: "+92" },
  { iso2: "BD", name: "Bangladesh", flag: "🇧🇩", dial: "+880" },
  { iso2: "EG", name: "Egypt", flag: "🇪🇬", dial: "+20" },
  { iso2: "MA", name: "Morocco", flag: "🇲🇦", dial: "+212" },
  { iso2: "DZ", name: "Algeria", flag: "🇩🇿", dial: "+213" },
  { iso2: "TN", name: "Tunisia", flag: "🇹🇳", dial: "+216" },
  { iso2: "ET", name: "Ethiopia", flag: "🇪🇹", dial: "+251" },
  { iso2: "TZ", name: "Tanzania", flag: "🇹🇿", dial: "+255" },
  { iso2: "UG", name: "Uganda", flag: "🇺🇬", dial: "+256" },
  { iso2: "RW", name: "Rwanda", flag: "🇷🇼", dial: "+250" },
  { iso2: "CM", name: "Cameroon", flag: "🇨🇲", dial: "+237" },
  { iso2: "CI", name: "Ivory Coast", flag: "🇨🇮", dial: "+225" },
  { iso2: "SN", name: "Senegal", flag: "🇸🇳", dial: "+221" },
  { iso2: "UA", name: "Ukraine", flag: "🇺🇦", dial: "+380" },
  { iso2: "RU", name: "Russia", flag: "🇷🇺", dial: "+7" },
  { iso2: "KZ", name: "Kazakhstan", flag: "🇰🇿", dial: "+7" },
  { iso2: "UZ", name: "Uzbekistan", flag: "🇺🇿", dial: "+998" },
  { iso2: "QA", name: "Qatar", flag: "🇶🇦", dial: "+974" },
  { iso2: "KW", name: "Kuwait", flag: "🇰🇼", dial: "+965" },
  { iso2: "OM", name: "Oman", flag: "🇴🇲", dial: "+968" },
  { iso2: "BH", name: "Bahrain", flag: "🇧🇭", dial: "+973" },
  { iso2: "JO", name: "Jordan", flag: "🇯🇴", dial: "+962" },
  { iso2: "LB", name: "Lebanon", flag: "🇱🇧", dial: "+961" },
  { iso2: "LK", name: "Sri Lanka", flag: "🇱🇰", dial: "+94" },
  { iso2: "NP", name: "Nepal", flag: "🇳🇵", dial: "+977" },
  { iso2: "MM", name: "Myanmar", flag: "🇲🇲", dial: "+95" },
  { iso2: "KH", name: "Cambodia", flag: "🇰🇭", dial: "+855" },
  { iso2: "LA", name: "Laos", flag: "🇱🇦", dial: "+856" },
  { iso2: "BN", name: "Brunei", flag: "🇧🇳", dial: "+673" },
  { iso2: "PE", name: "Peru", flag: "🇵🇪", dial: "+51" },
  { iso2: "EC", name: "Ecuador", flag: "🇪🇨", dial: "+593" },
  { iso2: "VE", name: "Venezuela", flag: "🇻🇪", dial: "+58" },
  { iso2: "CL", name: "Chile", flag: "🇨🇱", dial: "+56" },
  { iso2: "UY", name: "Uruguay", flag: "🇺🇾", dial: "+598" },
  { iso2: "PY", name: "Paraguay", flag: "🇵🇾", dial: "+595" },
  { iso2: "BO", name: "Bolivia", flag: "🇧🇴", dial: "+591" },
  { iso2: "DO", name: "Dominican Republic", flag: "🇩🇴", dial: "+1" },
  { iso2: "CR", name: "Costa Rica", flag: "🇨🇷", dial: "+506" },
  { iso2: "PA", name: "Panama", flag: "🇵🇦", dial: "+507" },
  { iso2: "GT", name: "Guatemala", flag: "🇬🇹", dial: "+502" },
  { iso2: "SV", name: "El Salvador", flag: "🇸🇻", dial: "+503" },
  { iso2: "HN", name: "Honduras", flag: "🇭🇳", dial: "+504" },
  { iso2: "NI", name: "Nicaragua", flag: "🇳🇮", dial: "+505" },
  { iso2: "JM", name: "Jamaica", flag: "🇯🇲", dial: "+1" },
  { iso2: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", dial: "+1" },
].sort((a, b) => a.name.localeCompare(b.name));

export const findCountry = (iso2: string) =>
  COUNTRIES.find((c) => c.iso2 === iso2.toUpperCase());
