/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardVoiceCallRouteImport } from './routes/dashboard.voice-call'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSendGiftsRouteImport } from './routes/dashboard.send-gifts'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMarketplaceRouteImport } from './routes/dashboard.marketplace'
import { Route as DashboardFundWalletRouteImport } from './routes/dashboard.fund-wallet'
import { Route as DashboardCartRouteImport } from './routes/dashboard.cart'
import { Route as DashboardBuyNumberRouteImport } from './routes/dashboard.buy-number'
import { Route as DashboardBulkSmsRouteImport } from './routes/dashboard.bulk-sms'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminTwilioRouteImport } from './routes/admin.twilio'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminApiConfigRouteImport } from './routes/admin.api-config'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio-status'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardVoiceCallRoute = DashboardVoiceCallRouteImport.update({
  id: '/voice-call',
  path: '/voice-call',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSendGiftsRoute = DashboardSendGiftsRouteImport.update({
  id: '/send-gifts',
  path: '/send-gifts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFundWalletRoute = DashboardFundWalletRouteImport.update({
  id: '/fund-wallet',
  path: '/fund-wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartRoute = DashboardCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuyNumberRoute = DashboardBuyNumberRouteImport.update({
  id: '/buy-number',
  path: '/buy-number',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBulkSmsRoute = DashboardBulkSmsRouteImport.update({
  id: '/bulk-sms',
  path: '/bulk-sms',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTwilioRoute = AdminTwilioRouteImport.update({
  id: '/twilio',
  path: '/twilio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiConfigRoute = AdminApiConfigRouteImport.update({
  id: '/api-config',
  path: '/api-config',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio-status',
  path: '/api/public/twilio-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/api-config': typeof AdminApiConfigRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/twilio': typeof AdminTwilioRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bulk-sms': typeof DashboardBulkSmsRoute
  '/dashboard/buy-number': typeof DashboardBuyNumberRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/fund-wallet': typeof DashboardFundWalletRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-gifts': typeof DashboardSendGiftsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/voice-call': typeof DashboardVoiceCallRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/api-config': typeof AdminApiConfigRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/twilio': typeof AdminTwilioRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bulk-sms': typeof DashboardBulkSmsRoute
  '/dashboard/buy-number': typeof DashboardBuyNumberRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/fund-wallet': typeof DashboardFundWalletRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-gifts': typeof DashboardSendGiftsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/voice-call': typeof DashboardVoiceCallRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/api-config': typeof AdminApiConfigRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/twilio': typeof AdminTwilioRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/bulk-sms': typeof DashboardBulkSmsRoute
  '/dashboard/buy-number': typeof DashboardBuyNumberRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/fund-wallet': typeof DashboardFundWalletRoute
  '/dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/send-gifts': typeof DashboardSendGiftsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/voice-call': typeof DashboardVoiceCallRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/api-config'
    | '/admin/approvals'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/twilio'
    | '/admin/upload'
    | '/admin/users'
    | '/dashboard/bulk-sms'
    | '/dashboard/buy-number'
    | '/dashboard/cart'
    | '/dashboard/fund-wallet'
    | '/dashboard/marketplace'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/send-gifts'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/dashboard/voice-call'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/twilio-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/api-config'
    | '/admin/approvals'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/twilio'
    | '/admin/upload'
    | '/admin/users'
    | '/dashboard/bulk-sms'
    | '/dashboard/buy-number'
    | '/dashboard/cart'
    | '/dashboard/fund-wallet'
    | '/dashboard/marketplace'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/send-gifts'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/dashboard/voice-call'
    | '/admin'
    | '/dashboard'
    | '/api/public/twilio-status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/api-config'
    | '/admin/approvals'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/products'
    | '/admin/twilio'
    | '/admin/upload'
    | '/admin/users'
    | '/dashboard/bulk-sms'
    | '/dashboard/buy-number'
    | '/dashboard/cart'
    | '/dashboard/fund-wallet'
    | '/dashboard/marketplace'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/send-gifts'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/dashboard/voice-call'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/twilio-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/voice-call': {
      id: '/dashboard/voice-call'
      path: '/voice-call'
      fullPath: '/dashboard/voice-call'
      preLoaderRoute: typeof DashboardVoiceCallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/send-gifts': {
      id: '/dashboard/send-gifts'
      path: '/send-gifts'
      fullPath: '/dashboard/send-gifts'
      preLoaderRoute: typeof DashboardSendGiftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketplace': {
      id: '/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fund-wallet': {
      id: '/dashboard/fund-wallet'
      path: '/fund-wallet'
      fullPath: '/dashboard/fund-wallet'
      preLoaderRoute: typeof DashboardFundWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart': {
      id: '/dashboard/cart'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buy-number': {
      id: '/dashboard/buy-number'
      path: '/buy-number'
      fullPath: '/dashboard/buy-number'
      preLoaderRoute: typeof DashboardBuyNumberRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bulk-sms': {
      id: '/dashboard/bulk-sms'
      path: '/bulk-sms'
      fullPath: '/dashboard/bulk-sms'
      preLoaderRoute: typeof DashboardBulkSmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/twilio': {
      id: '/admin/twilio'
      path: '/twilio'
      fullPath: '/admin/twilio'
      preLoaderRoute: typeof AdminTwilioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-config': {
      id: '/admin/api-config'
      path: '/api-config'
      fullPath: '/admin/api-config'
      preLoaderRoute: typeof AdminApiConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/twilio-status': {
      id: '/api/public/twilio-status'
      path: '/api/public/twilio-status'
      fullPath: '/api/public/twilio-status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApiConfigRoute: typeof AdminApiConfigRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminTwilioRoute: typeof AdminTwilioRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiConfigRoute: AdminApiConfigRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminTwilioRoute: AdminTwilioRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBulkSmsRoute: typeof DashboardBulkSmsRoute
  DashboardBuyNumberRoute: typeof DashboardBuyNumberRoute
  DashboardCartRoute: typeof DashboardCartRoute
  DashboardFundWalletRoute: typeof DashboardFundWalletRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSendGiftsRoute: typeof DashboardSendGiftsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardVoiceCallRoute: typeof DashboardVoiceCallRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBulkSmsRoute: DashboardBulkSmsRoute,
  DashboardBuyNumberRoute: DashboardBuyNumberRoute,
  DashboardCartRoute: DashboardCartRoute,
  DashboardFundWalletRoute: DashboardFundWalletRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSendGiftsRoute: DashboardSendGiftsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardVoiceCallRoute: DashboardVoiceCallRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
